server.servlet.context-path=/template/api/
server.port=8080
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/template?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Dew@2005
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

security.jwt.expire=900000000
security.jwt.refresh.expire=1800000
security.jwt.secret=Jd9Xw8LzQy3Mv0NgTkRb6PY2fCZG1A5KpW7HqB4FsVJxNDYrtml8cGzXQW9yKZPj34hcuYGSacdcsacndsfb874UGE78chsuh437bhdwy78dy8csacNneu3

login.success.message=Login successful
login.incorrect.message=Incorrect username or password
user.notfound.message=User not found
login.lock.message=Account has been locked